# Generated by Django 4.2.23 on 2025-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
